systemd-boot: warn if efibootmgr is not installed
As it means the boot entry won't be created, since it's a recommends

diff --git a/debian/systemd-boot.postinst b/debian/systemd-boot.postinst
--- a/debian/systemd-boot.postinst
+++ b/debian/systemd-boot.postinst
@@ -119,7 +119,9 @@ install_shim() {
         echo "shim${efi_arch}.efi,${vendor},,This is the boot entry for ${vendor}" > "${esp_path}/EFI/${vendor}/BOOT${efi_arch_upper}.CSV"
     fi
 
-    if command -v efibootmgr >/dev/null 2>&1 && ! efibootmgr | grep -q "Boot.*${vendor_upper}.*EFI\\\\${vendor}\\\\shim${efi_arch}.efi"; then
+    if ! command -v efibootmgr >/dev/null 2>&1; then
+        echo "efibootmgr not found, skipping boot entry creation"
+    elif ! efibootmgr | grep -q "Boot.*${vendor_upper}.*EFI\\\\${vendor}\\\\shim${efi_arch}.efi"; then
         blkpart="$(findmnt -nvo SOURCE "$esp_path")"
         if [ ! -L "/sys/class/block/${blkpart##*/}" ]; then
             return
