Import http://deb.debian.org/debian/pool/main/s/systemd/systemd_247.2-5.debian.tar.xz

diff --git a/debian/systemd.postinst b/debian/systemd.postinst
--- a/debian/systemd.postinst
+++ b/debian/systemd.postinst
@@ -1,4 +1,4 @@
-#! /bin/sh
+#!/bin/sh
 
 set -e
 
@@ -12,19 +12,9 @@ _update_catalog() {
     journalctl --update-catalog || true
 }
 
-# Update Message Catalogs database and reload in response to dpkg triggers
+# Update Message Catalogs database in response to dpkg trigger
 if [ "$1" = "triggered" ]; then
-    shift
-    for trigger in "$@"; do
-        case $trigger in
-            /usr/lib/systemd/catalog)
-                _update_catalog
-                ;;
-            /etc/init.d)
-                _systemctl daemon-reload || true
-                ;;
-        esac
-    done
+    _update_catalog
     exit 0
 fi
 
@@ -34,14 +24,9 @@ if [ -z "$2" ]; then
     systemctl enable remote-fs.target || true
 fi
 
-# Enable timesyncd by default on new installs installs and upgrades
-if dpkg --compare-versions "$2" lt "218-11~"; then
-    systemctl enable systemd-timesyncd.service || true
-fi
-
-# Enable ondemand by default on new installs installs and upgrades
-if [ -e /lib/systemd/system/ondemand.service ] && dpkg --compare-versions "$2" lt "231-7~"; then
-    systemctl enable ondemand.service || true
+# Enable systemd-pstore by default on new installs and upgrades, see #952767
+if dpkg --compare-versions "$2" lt "245.4-4~"; then
+    systemctl enable systemd-pstore.service || true
 fi
 
 # Do a one-time migration of the local time setting
@@ -96,29 +81,21 @@ systemd-machine-id-setup
 # Setup system users and groups
 addgroup --quiet --system systemd-journal
 
-# We need to stop running services before we call adduser
-RESTART=""
-if dpkg --compare-versions "$2" lt-nl "239-6"; then
-    for s in systemd-networkd systemd-timesyncd systemd-resolved ; do
-        if _systemctl -q is-active $s; then
-            _systemctl stop $s
-            RESTART="$s $RESTART"
-        fi
-    done
-fi
-
-adduser --quiet --system --group --no-create-home --home /run/systemd \
-    --gecos "systemd Time Synchronization" systemd-timesync
 adduser --quiet --system --group --no-create-home --home /run/systemd \
     --gecos "systemd Network Management" systemd-network
 adduser --quiet --system --group --no-create-home --home /run/systemd \
     --gecos "systemd Resolver" systemd-resolve
 
-# Remove old state directory of systemd-timesyncd
-if dpkg --compare-versions "$2" lt-nl "240-3~"; then
-    if [ -L /var/lib/systemd/timesync ] ; then
-        rm /var/lib/systemd/timesync
-        rm -rf /var/lib/private/systemd/timesync
+# Enable persistent journal, in auto-mode, by default on new installs and upgrades
+if dpkg --compare-versions "$2" lt "244.1-2~"; then
+    mkdir -p /var/log/journal
+    # Applying ACLs requires a mounted /proc and systemd-tmpfiles will fail if
+    # /proc is not available. Skip systemd-tmpfiles in this case. This should
+    # be fine, as this typically means we are inside a chroot and systemd is
+    # not currently active. The permissions will be applied on the next boot.
+    # https://github.com/systemd/systemd/issues/14745
+    if mountpoint -q /proc; then
+        systemd-tmpfiles --create --prefix /var/log/journal
     fi
 fi
 
@@ -129,26 +106,13 @@ if [ -n "$2" ]; then
     _systemctl daemon-reexec || true
     # don't restart logind; this can be done again once this gets implemented:
     # https://github.com/systemd/systemd/issues/1163
+    if dpkg --compare-versions "$2" lt-nl "246.2-2~"; then
+        # the socket configuration changed
+        _systemctl stop systemd-networkd.socket || true
+    fi
     _systemctl try-restart systemd-networkd.service || true
     _systemctl try-restart systemd-resolved.service || true
-    _systemctl try-restart systemd-timesyncd.service || true
     _systemctl try-restart systemd-journald.service || true
-fi
-
-# Restart services which we stopped earlier
-# This needs to run after daemon-rexec
-if dpkg --compare-versions "$2" lt-nl "239-6"; then
-    for s in $RESTART ; do
-        _systemctl start $s
-    done
-fi
-
-# Cleanup hwclock-save.service, which was shipped in jessie.
-if dpkg --compare-versions "$2" lt-nl "228-5~"; then
-   for t in reboot halt poweroff ; do
-       rm -f /etc/systemd/system/${t}.target.wants/hwclock-save.service
-       rmdir --ignore-fail-on-non-empty /etc/systemd/system/${t}.target.wants 2> /dev/null || true
-   done
 fi
 
 if dpkg --compare-versions "$2" lt-nl "235-3~"; then
@@ -168,6 +132,17 @@ if dpkg --compare-versions "$2" lt-nl "239-12~"; then
     if getent group nobody >/dev/null; then
         delgroup --system nobody || true
     fi
+fi
+
+if dpkg --compare-versions "$2" lt-nl "245.4-4~"; then
+    # systemd-pstore.service is now enabled via sysinit.target
+    rm -f /etc/systemd/system/systemd-remount-fs.service.wants/systemd-pstore.service
+    rmdir --ignore-fail-on-non-empty /etc/systemd/system/systemd-remount-fs.service.wants 2> /dev/null || true
+fi
+
+if dpkg --compare-versions "$2" lt-nl "245.4-5~"; then
+    # Clean up removed ondemand service
+    rm -f /etc/systemd/system/multi-user.target.wants/ondemand.service
 fi
 
 #DEBHELPER#
diff --git a/debian/tests/boot-smoke b/debian/tests/boot-smoke
--- a/debian/tests/boot-smoke
+++ b/debian/tests/boot-smoke
@@ -8,8 +8,11 @@ set -e
 . `dirname $0`/assert.sh
 
 fail() {
+    [ -n "$1" ] && echo "$1"
+    set +e
     journalctl --sync
     journalctl -a > "$AUTOPKGTEST_ARTIFACTS/boot-smoke-journal.txt"
+    systemctl --no-pager --no-legend list-jobs > "$AUTOPKGTEST_ARTIFACTS/boot-smoke-running-jobs.txt"
     udevadm info --export-db > "$AUTOPKGTEST_ARTIFACTS/boot-smoke-udevdb.txt"
     exit 1
 }
@@ -36,31 +39,43 @@ EOF
         done
     fi
 else
+    echo "waiting to boot..."
+    TIMEOUT=35
+    while [ $TIMEOUT -ge 0 ]; do
+        state="$(systemctl is-system-running || true)"
+        case $state in
+            running|degraded)
+                break
+                ;;
+            *)
+                sleep 1
+                TIMEOUT=$((TIMEOUT - 1))
+		;;
+        esac
+    done
+
+    echo "checking for running system"
+    if [ "$state" = "degraded" ]; then
+        systemctl --no-pager --no-legend --failed list-units > "$AUTOPKGTEST_ARTIFACTS/boot-smoke-failed-units.txt" || true
+        echo "systemctl is-system-running: degraded (non-fatal)"
+    elif [ "$state" != "running" ]; then
+        fail "system not running after timeout $RUNNING_TIMEOUT, state: $state"
+    fi
+
     echo "checking for failed unmounts for user systemd"
     # grep complete journal to catch shutdown messages
     if journalctl | grep -E "systemd\[([2-9]|[1-9][0-9]+)\].*Failed unmounting"; then
-        fail
+        fail "found failed unmount in journal"
     fi
+
     # grep only this boot's journal, earlier ones complain about missing "render" group
     echo "checking for connection timeouts"
     if journalctl -b | grep "Connection timed out"; then
-        fail
+        fail "found connection timeout in journal for this boot"
     fi
 
-    echo "checking that polkitd runs"
-    pidof polkitd
-
-    echo "checking that there are no running jobs"
-    TIMEOUT=10
-    while [ $TIMEOUT -ge 0 ]; do
-        running="$(systemctl --no-pager --no-legend list-jobs || true)"
-        [ -n "$running" ] || break
-        TIMEOUT=$((TIMEOUT - 1))
-    done
-    if [ -n "$running" ]; then
-        echo "running jobs after remaining timeout $TIMEOUT: $running"
-        fail
-    fi
+    echo "checking that NetworkManager runs"
+    pidof NetworkManager || fail "NetworkManager was not running"
 fi
 
 if [ "$AUTOPKGTEST_REBOOT_MARK" -ge 5 ]; then
diff --git a/debian/tests/upstream b/debian/tests/upstream
--- a/debian/tests/upstream
+++ b/debian/tests/upstream
@@ -3,18 +3,7 @@
 # Author: Martin Pitt <martin.pitt@ubuntu.com>
 set -e
 
-# even after installing policycoreutils this fails with
-# "Failed to install /usr/libexec/selinux/hll/pp"
-BLACKLIST="TEST-06-SELINUX"
-
-# some tests are flaky
-BLACKLIST="$BLACKLIST
-TEST-02-CRYPTSETUP
-TEST-10-ISSUE-2467
-TEST-13-NSPAWN-SMOKE
-TEST-16-EXTEND-TIMEOUT
-TEST-17-UDEV-WANTS
-"
+DPKGARCH=$(dpkg --print-architecture)
 
 # quiesce Makefile.guess; not really relevant as systemd/nspawn run from
 # installed packages
@@ -30,21 +19,44 @@ sed -i 's_/usr/libexec/selinux/hll/pp_/usr/lib/selinux/hll/pp_' test/TEST-06-SEL
 
 FAILED=""
 
+# Because this test is used both by upstream and by Debian, we use different deny-list filenames.
+# For more details see https://salsa.debian.org/systemd-team/systemd/merge_requests/52
+# The naming is transitioning from blacklist to deny-list, so currently both are supported
+# More details in https://github.com/systemd/systemd/pull/16262
+if [ -n "$TEST_UPSTREAM" ]; then
+    DENY_LIST="deny-list-ubuntu-ci"
+    BLACKLIST="blacklist-ubuntu-ci"
+else
+    DENY_LIST="deny-list-upstream-ci"
+    BLACKLIST="blacklist-upstream-ci"
+fi
+
 for t in test/TEST*; do
-    echo "$BLACKLIST" | grep -q "$(basename $t)" && continue
-    echo "========== `basename $t` =========="
+    testname=$(basename $t)
+    if [ -f "$t/${DENY_LIST}" -o -f "$t/${BLACKLIST}" ]; then
+        echo "========== DENY-LISTED: $testname =========="
+        continue
+    elif [ -f "$t/${DENY_LIST}-$DPKGARCH" -o -f "$t/${BLACKLIST}-$DPKGARCH" ]; then
+        echo "========== DENY-LISTED (for arch $DPKGARCH): $testname =========="
+        continue
+    fi
+    echo "========== START: $testname =========="
     rm -rf /var/tmp/systemd-test.*
-    if ! make -C $t setup run clean; then
-        for j in /var/tmp/systemd-test.*/journal/*; do
+    if ! make -C $t clean setup run; then
+        for j in /var/tmp/systemd-test.*/journal/* /var/tmp/systemd-test.*/system.journal; do
             [ -e "$j" ] || continue
             # keep the entire journal in artifacts, in case one needs the debug messages
-            cp -r "$j" "$AUTOPKGTEST_ARTIFACTS/$(basename $t)-$(basename $j)"
+            cp -r "$j" "$AUTOPKGTEST_ARTIFACTS/${testname}-$(basename $j)"
             echo "---- $j ----"
-            journalctl --priority=warning --directory=$j
+            [ -d "$j" ] && journalctl --priority=warning --directory=$j
+            [ -f "$j" ] && journalctl --priority=warning --file=$j
         done
-        FAILED="$FAILED $t"
+        FAILED="$FAILED $testname"
     fi
     echo
+    # always cleanup each test run
+    make -C $t clean-again
+    echo "========== END: $testname =========="
 done
 
 if [ -n "$FAILED" ]; then
